//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arad.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AradEntities : DbContext
    {
        public AradEntities()
            : base("name=AradEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<Person> Person { get; set; }
        public virtual DbSet<Role> Role { get; set; }
<<<<<<< HEAD
        public virtual DbSet<Salon> Salon { get; set; }
        public virtual DbSet<Sance> Sance { get; set; }
        public virtual DbSet<Team> Team { get; set; }
        public virtual DbSet<Team_Account> Team_Account { get; set; }
        public virtual DbSet<Salon_Sance> Salon_Sance { get; set; }
=======
>>>>>>> aa73389685fc8c13d5ef59744930e1a7f20df9ed
    }
}
