//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Family { get; set; }
        public Nullable<int> Age { get; set; }
        public string NationalCode { get; set; }
        public string FahterName { get; set; }
        public Nullable<int> province { get; set; }
        public Nullable<int> City { get; set; }
        public Nullable<int> Ranc { get; set; }
        public string Image { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
