//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Play
    {
        public int Id { get; set; }
        public Nullable<int> RequestId { get; set; }
        public Nullable<int> HostTeamScore { get; set; }
        public Nullable<int> GuestTeamScore { get; set; }
    
        public virtual Request Request { get; set; }
    }
}
